board/blogs/urls.py
from django.urls import path, include
from .views import (
    post_list,
    post_create,
    post_edit,
    post_delete,
    post_detail,
    post_like,
)

app_name = "blog"

urlpatterns = [
    # http://127.0.0.1:8000/blogs/
    path("", post_list, name="post_list"),
    # http://127.0.0.1:8000/blogs/create
    path("create/", post_create, name="post_create"),
    # http://127.0.0.1:8000/blogs/detail/1/
    path("detail/<int:post_id>/", post_detail, name="post_detail"),
    # http://127.0.0.1:8000/blogs/edit/1/
    path("edit/<int:post_id>/", post_edit, name="post_edit"),
    # http://127.0.0.1:8000/blogs/delete/1/
    path("delete/<int:post_id>/", post_delete, name="post_delete"),
    # http://127.0.0.1:8000/blogs/likes/1/
    path("likes/<int:post_id>/", post_like, name="post_like"),
]

board/board/urls.py
from django.urls import path
from .views.base_views import index, question_detail
from .views.question_views import (
    question_create,
    question_edit,
    question_delete,
    vote_question,
)
from .views.answer_views import answer_create, answer_edit, answer_delete, vote_answer
from .views.comment_views import (
    comment_create_question,
    comment_edit_question,
    comment_delete_question,
    comment_create_answer,
    comment_edit_answer,
    comment_delete_answer,
)

app_name = "board"

urlpatterns = [
    # http://127.0.0.1:8000/board/
    path("", index, name="index"),
    # http://127.0.0.1:8000/board/1/ 상세조회
    path("<int:qid>/", question_detail, name="detail"),
    # http://127.0.0.1:8000/board/question/create/ 질문등록
    path("question/create/", question_create, name="question_create"),
    # http://127.0.0.1:8000/board/question/modify/1/ 질문수정
    path("question/modify/<int:qid>/", question_edit, name="question_modify"),
    # http://127.0.0.1:8000/board/question/delete/1/ 질문삭제
    path("question/delete/<int:qid>/", question_delete, name="question_delete"),
    # 답변
    # http://127.0.0.1:8000/board/answer/create/질문번호/
    path("answer/create/<int:qid>/", answer_create, name="answer_create"),
    # http://127.0.0.1:8000/board/answer/modify/답변번호/
    path("answer/modify/<int:aid>/", answer_edit, name="answer_modify"),
    # http://127.0.0.1:8000/board/answer/delete/답변번호/
    path("answer/delete/<int:aid>/", answer_delete, name="answer_delete"),
    # 질문 댓글
    # 질문 댓글 추가
    path(
        "comment/create/question/<int:qid>/",
        comment_create_question,
        name="comment_create_question",
    ),
    # 질문 댓글 수정
    path(
        "comment/edit/question/<int:comment_id>/",
        comment_edit_question,
        name="comment_edit_question",
    ),
    # 질문 댓글 삭제
    path(
        "comment/delete/question/<int:comment_id>/",
        comment_delete_question,
        name="comment_delete_question",
    ),
    # 답변 댓글
    # 답변 댓글 추가
    path(
        "comment/create/answer/<int:aid>/",
        comment_create_answer,
        name="comment_create_answer",
    ),
    # 답변 댓글 수정
    path(
        "comment/edit/answer/<int:comment_id>/",
        comment_edit_answer,
        name="comment_edit_answer",
    ),
    # 답변 댓글 삭제
    path(
        "comment/delete/answer/<int:comment_id>/",
        comment_delete_answer,
        name="comment_delete_answer",
    ),
    # 추천
    # 질문 추천
    path("vote/question/<int:qid>/", vote_question, name="vote_question"),
    # 답변 추천
    path("vote/answer/<int:aid>/", vote_answer, name="vote_answer"),
]

board/config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views.base_views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("users/", include("users.urls")),
    path("blogs/", include("blogs.urls")),
    # http://127.0.0.1:8000/
    path("", index, name="index"),
]

board/board/models.py
from django.db import models
from django.contrib.auth.models import User

# Question, Answer 모델에서 author, voter 두 개의 필드가 User 모델 참조
# user.question_set  이렇게 Question 모델에 접근할 때 어느 필드가 기준이냐? 를 알려줘야 함
# 특정 필드에 이름만 부여 해놓기 : related_name


# Question 테이블
# 번호(자동생성),제목,내용,작성날짜,수정날짜
class Question(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_question"
    )
    subject = models.CharField(max_length=200, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    # auto_now_add : insert 시 자동으로 시간/날짜 삽입
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(verbose_name="수정날짜", null=True, blank=True)
    # 추천 필드
    voter = models.ManyToManyField(User, related_name="voter_question")
    # 조회수
    view_cnt = models.BigIntegerField(default=0)

    def __str__(self) -> str:
        return self.subject


# Answer 테이블
# 번호(자동생성),외래키 제약,내용,작성날짜,수정날짜
class Answer(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_answer"
    )
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(verbose_name="수정날짜", null=True, blank=True)
    # 추천 필드
    voter = models.ManyToManyField(User, related_name="voter_answer")


# 댓글 테이블
# 질문, 답변 댓글 모두 저장 ==> 구분은 어떻게 할 것인가?
# 번호(자동생성),작성자,댓글내용,작성날짜,수정날짜,외래키(질문,답변 구분을 위해)
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="작성자")
    content = models.TextField(verbose_name="댓글내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(verbose_name="수정날짜", null=True, blank=True)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, null=True, blank=True
    )
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, blank=True)


class QuestionCount(models.Model):
    """
    조회수 업데이트를 위한 모델
    사용자의 ip 저장
    """

    ip = models.CharField(max_length=30)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.ip

board/board/forms.py
from .models import Question, Answer, Comment
from django import forms

"""
django - 화면 디자인 처리
1. html : 일반적인 처리(bootstrap 이용, 직접 디자인)
2. 장고의 form 클래스 이용
   forms.ModelForm, forms.Form 클래스를 상속받고 작성
"""


# class NameForm(forms.Form):
#     # 화면에 보여줄 요소
#     name = forms.CharField(
#         label="name", max_length=100, error_messages={"required": "이름입력"}
#     )


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["subject", "content"]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["content"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

board/board/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from ..models import Question, Answer
from ..forms import AnswerForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages


@login_required(login_url="users:login")
def answer_create(request, qid):
    """
    답변등록
    1) question 을 이용해 답변 등록
    question.answer_set.create()

    2) insert into answer(content,qid) values('답변',1)
    question = get_object_or_404(Question,id=qid)
    answer = Answer(question=question,content=request.POST[''])
    answer.save()
    """

    # form 사용하지 않는 방식
    # question = get_object_or_404(Question, id=qid)
    # save() 명령어 안해도 됨
    # question.answer_set.create(content=request.POST["content"])

    # form 사용방식
    question = get_object_or_404(Question, id=qid)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            # form.save() : commit 은 default 가 True 상태로 db 바로 반영
            answer = form.save(commit=False)
            # 어느 질문에 대한 답변인가?
            answer.question = question
            answer.author = request.user
            answer.save()
            # return redirect("board:detail", qid=qid)
            # detail 앵커 이용
            return redirect(
                "{}#answer_{}".format(resolve_url("board:detail", qid=qid), answer.id)
            )
    else:
        form = AnswerForm()
    context = {"question": question, "form": form}
    return render(request, "board/question_detail.html", context)


@login_required(login_url="users:login")
def answer_edit(request, aid):
    """
    get : 수정 화면 보여주기
          수정 답변 찾기 => 수정 답변 폼과 연결하기
    post : 답변 수정
           수정 성공 시 detail 이동
    """

    answer = get_object_or_404(Answer, id=aid)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modified_at = timezone.now()
            answer.save()
            # return redirect("board:detail", qid=answer.question_id)
            return redirect(
                "{}#answer_{}".format(
                    resolve_url("board:detail", qid=answer.question_id), answer.id
                )
            )
    else:
        form = AnswerForm(instance=answer)

    return render(request, "board/answer_edit.html", {"form": form})


def answer_delete(request, aid):
    """
    답변 삭제 후 detail 이동
    """
    answer = get_object_or_404(Answer, id=aid)
    answer.delete()

    # qid = answer.question_id(테이블 필드명 이용)
    # qid = answer.question.id
    return redirect("board:detail", qid=answer.question.id)


# 답변 추천
@login_required(login_url="users:login")
def vote_answer(request, aid):
    # answer 찾기
    answer = get_object_or_404(Answer, id=aid)

    # 로그인 사용자와 답변 작성자가 동일할 때
    # 본인이 작성한 글은 추천 불가 라는 메세지 보여주기
    if request.user == answer.author:
        messages.error(request, "본인이 작성한 글은 추천할 수 없습니다.")
    else:
        # 추천 user 추가
        answer.voter.add(request.user)
    # detail 이동
    return redirect("board:detail", qid=answer.question.id)

board/board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question, QuestionCount

from django.core.paginator import Paginator

# 필터링 여러 개 조건 사용할 때 이용
from django.db.models import Q, Count

from tools.utils import get_client_ip


"""
페이지 나누기
Paginator 클래스
Paginator(전체리스트, 페이지당 보여줄개수)

has_previous : 이전 페이지 유무
has_next : 다음 페이지 유무

previous_page_number : 이전 페이지 번호
next_page_number : 다음 페이지 번호
number : 현재 페이지 번호
page_range : 페이지 범위
count : 전체 게시물 개수
start_index : 현재 페이지 인덱스(1부터 시작)
"""


def index(request):
    # 질문 목록

    # 페이지 나누기 - 사용자가 요청한 페이지 가져오기
    # http://127.0.0.1:8000/board/?keyword=테스트&page=1&sort=recommend
    # page = request.GET['page']
    page = request.GET.get("page", 1)
    keyword = request.GET.get("keyword", "")
    sort = request.GET.get("sort", "recent")

    # select * from question
    # question_list = Question.objects.all()

    # select * from question order by created_at desc
    if sort == "recommend":  # 추천순
        question_list = Question.objects.annotate(num_voter=Count("voter")).order_by(
            "-num_voter", "-created_at"
        )
    elif sort == "popular":  # 인기순
        question_list = Question.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-created_at"
        )
    else:  # 최신순
        question_list = Question.objects.order_by("-created_at")

    # 전체 질문 리스트에서 검색어를 기준으로 필터링 하기
    # 제목,내용,질문작성자,답변작성자
    # __contains : 대소문자 구별, __icontains : 대소문자 구별없이
    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword)
            | Q(content__icontains=keyword)
            | Q(author__username__icontains=keyword)
            | Q(answer__author__username__icontains=keyword)
        ).distinct()

    paginator = Paginator(question_list, 10)
    # pageinator 사용자가 요청한 페이지 정보 담기
    page_obj = paginator.get_page(page)

    context = {
        "question_list": page_obj,
        "page": page,
        "keyword": keyword,
        "sort": sort,
    }

    return render(request, "board/question_list.html", context)


def question_detail(request, qid):
    page = request.GET.get("page")
    keyword = request.GET.get("keyword")
    sort = request.GET.get("sort")

    # qid 조회
    # select * from question where id=qid
    # get_object_or_404(), get(), filter()
    question = get_object_or_404(Question, id=qid)
    # question = Question.objects.get(id=qid)

    # 조회수 증가
    # client ip 가져오기
    ip = get_client_ip(request)

    cnt = QuestionCount.objects.filter(ip=ip, question=question).count()

    if cnt == 0:
        # QuestionCount 테이블에 ip와 question 추가
        qc = QuestionCount(ip=ip, question=question)
        qc.save()
        # Question 테이블에 조회수 증가
        if question.view_cnt:
            question.view_cnt += 1
        else:
            question.view_cnt = 1
        question.save()

    context = {
        "question": question,
        "page": page,
        "keyword": keyword,
        "sort": sort,
    }

    return render(request, "board/question_detail.html", context)

board/board/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from ..models import Question, Answer, Comment
from ..forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone


##################### 질문 댓글
@login_required(login_url="users:login")
def comment_create_question(request, qid):
    """
    질문 댓글 추가 - question id 가 필요함
    """
    # 질문찾기
    question = get_object_or_404(Question, id=qid)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)  # form 안에는 user,question 정보가 없음
            comment.author = request.user
            comment.question = question
            comment.save()
            # return redirect("board:detail", qid=qid)
            # name 앵커 이용
            return redirect(
                "{}#comment_{}".format(resolve_url("board:detail", qid=qid), comment.id)
            )
    else:
        form = CommentForm()

    return render(request, "board/comment_form.html", {"form": form})


@login_required(login_url="users:login")
def comment_edit_question(request, comment_id):
    """
    댓글 수정 - 댓글 id
    """
    # 댓글 하나 가져오기
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)  # modified_at 추가
            comment.modified_at = timezone.now()
            comment.save()
            # return redirect("board:detail", qid=comment.question.id)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:detail", qid=comment.question.id), comment.id
                )
            )
    else:
        form = CommentForm(instance=comment)

    return render(request, "board/comment_form.html", {"form": form})


@login_required(login_url="users:login")
def comment_delete_question(request, comment_id):
    """
    댓글 삭제 - 댓글 id
    """
    # 댓글 하나 가져오기
    comment = get_object_or_404(Comment, id=comment_id)

    # 댓글 삭제
    comment.delete()

    # detail 로 이동
    return redirect("board:detail", qid=comment.question.id)


##################### 답변 댓글
@login_required(login_url="users:login")
def comment_create_answer(request, aid):
    """
    답변 댓글 추가
    """

    answer = get_object_or_404(Answer, id=aid)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)  # 작성자,답변번호가 없음
            comment.author = request.user
            comment.answer = answer
            comment.save()
            # return redirect("board:detail", qid=answer.question.id)
            # name 앵커 이용
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:detail", qid=answer.question.id), comment.id
                )
            )
    else:
        form = CommentForm()
    return render(request, "board/comment_form.html", {"form": form})


@login_required(login_url="users:login")
def comment_edit_answer(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)  # modified_at 추가
            comment.modified_at = timezone.now()
            comment.save()
            # return redirect("board:detail", qid=comment.answer.question.id)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:detail", qid=comment.answer.question.id),
                    comment.id,
                )
            )
    else:
        form = CommentForm(instance=comment)
    return render(request, "board/comment_form.html", {"form": form})


@login_required(login_url="users:login")
def comment_delete_answer(request, comment_id):
    """
    답변 댓글 삭제
    댓글 찾은 후 삭제 => detail 이동
    """
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    # question 의 id 값 없는 상태 : 답변 댓글이기 때문에
    # answer 를 통해 question 값 얻어와야 함
    return redirect("board:detail", qid=comment.answer.question.id)

board/templates/board/answer_edit.html
{% extends 'base.html' %}
{% block contents %}
  <h5 class="my-3 border-bottom pb-2">답변 수정</h5>
  <!-- views.py 의 is_valid() 통과 못할 때-->
  {% include 'errors.html' %}
  <form method="post" class="my-3">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="content">내용</label>
      <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
    </div>
    <input type="submit" value="답변수정" class="btn btn-success">
  </form>
{% endblock contents %}

{{form.as_p}}

board/templates/board/comment_form.html
{% extends 'base.html' %}
{% block contents %}
  <h5 class="my-3 border-bottom pb-2">댓글</h5>
  <!-- views.py 의 is_valid() 통과 못할 때-->
  {% include 'errors.html' %}
  <form method="post" class="my-3">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="content">내용</label>
      <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
    </div>
    <input type="submit" value="댓글작성" class="btn btn-success">
  </form>
{% endblock contents %}

{{form.as_p}}

board/templates/board/question_create.html
{% extends 'base.html' %}
{% block contents %}
  <h5 class="my-3 border-bottom pd-2">질문 등록</h5>
  <!-- views.py is_valid() 통과 못할 때-->
  {% include 'errors.html' %}
  <form method="post" class="my-3">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="subject">제목</label>
      <input type="text" name="subject" id-"subject"="id-" subject""="subject" "" class="form-control" value="{{form.subject.value|default_if_none:''}}">
    </div>
    <div class="form-group mb-3">
      <label for="content">내용</label>
      <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-success">
  </form>
{% endblock contents %}

{{form.as_p}}

board/templates/board/question_detail.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <style>
    .comment {
      border-top: dotted 1px #ddd;
      font-size: 0.7em;
    }
  </style>
{% endblock style %}
{% block contents %}
  <h2 class="border-bottom py-2">
    <!-- 질문제목-->
    {{question.subject}}
  </h2>
  <!-- 추천 영역-->
  <div class="row my-3">
    <!-- 자신의 글 추천할 수 없음 메세지 영역-->
    {% if messages %}
      <div class="alert alert-danger my-3">
        {% for msg in messages %}
          <strong>{{msg.tags}}</strong>
          <ul>
            <li>{{msg.message}}</li>
          </ul>
        {% endfor %}
      </div>
    {% endif %}
    <div class="col-1">
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
        <!--추천수-->
        {{question.voter.count}}
      </div>
      <div class="d-grid d-block">
        <a href="{% url 'board:vote_question' question.id %}" class="recommand btn btn-sm btn-secondary">추천</a>
      </div>
    </div>
    <div class="col-11">
      <div class="card">
        <div class="card-body">
          <div class="card-text">
            <!--질문내용-->
            {{question.content}}
          </div>
          <div class="d-flex justify-content-end">
            <div class="badge text-bg-light p-2 text-start">
              <div class="mb-2">
                <!--작성자-->
                {{question.author}}
              </div>
              <!--질문작성날짜-->
              {{question.created_at}}
            </div>
          </div>
          <!--수정 날짜-->
          <div class="d-flex justify-content-end">
            {% if question.modified_at %}
              <div class="badge text-bg-light p-2 text-start">
                <div class="mb-2">modified_at</div>
                <!--질문수정날짜-->
                {{question.modified_at|date}}
              </div>
            {% endif %}
          </div>
          <!--// 수정 날짜 종료-->
          <!-- 로그인 사용자와 작성자가 동일한 경우만 -->
          {% if request.user == question.author %}
            <div class="my-3">
              <a href="{% url 'board:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
              <a href="{% url 'board:question_delete' question.id %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
            </div>
          {% endif %}
          <!-- 질문 댓글 영역-->
          {% if question.comment_set.count > 0 %}
            <div class="mt-3">
              {% for comment in question.comment_set.all %}
                <a name="comment_{{comment.id}}"></a>
                <div class="comment py-2 text-muted">
                  <span style="white-space:pre-line">{{comment.content}}</span>
                  <span>
                    <!--댓글 작성자 / 작성일시 / 수정일시-->
                    -
                    {{comment.author}},
                    {{comment.created_at}}
                    {% if comment.modified_at %}
                      (수정 :
                      {{comment.modified_at|date}})
                    {% endif %}
                  </span>
                  {% if request.user == comment.author %}
                    <a href="{% url 'board:comment_edit_question' comment.id %}" class="small">수정</a>
                    <a href="{% url 'board:comment_delete_question' comment.id %}" class="small delete">삭제</a>
                  {% endif %}
                </div>
              {% endfor %}
            </div>
          {% endif %}
        </div>
        <div class="mx-3">
          <a href="{% url 'board:comment_create_question' question.id %}" class="small">댓글추가....</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Answer 영역 question 과 answer 외래키 제약조건 상태 question.answer_set question.answer_set.count : question 달린 댓글 개수 question.answer_set.all : question 달린 댓글 전체 -->
  <h5 class="border-bottom py-2 my-3">
    <!-- 답변 개수-->
    {{question.answer_set.count}}
    개의 답변이 있습니다.
  </h5>
  {% for answer in question.answer_set.all%}
    <a name="answer_{{answer.id}}"></a>
    <!-- 추천 영역-->
    <div class="row my-3">
      <div class="col-1">
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
          <!--추천수 : select count(*) from board_answer_voter where answer_id = 205 -->
          {{answer.voter.count}}
        </div>
        <div class="d-grid d-block">
          <a href="{% url 'board:vote_answer' answer.id %}" class="recommand btn btn-sm btn-secondary">추천</a>
        </div>
      </div>
      <div class="col-11">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <!--답변내용-->
              {{answer.content}}
            </div>
            <div class="d-flex justify-content-end">
              <div class="badge text-bg-light p-2 text-start">
                <!--답변 작성자-->
                <div class="mb-2">
                  {{answer.author}}
                </div>
                <!--답변작성날짜-->
                {{answer.created_at}}
              </div>
            </div>
            <!--답변 수정 날짜-->
            <div class="d-flex justify-content-end">
              {% if answer.modified_at %}
                <div class="badge text-bg-light p-2 text-start">
                  <div class="mb-2">modified_at</div>
                  <!--답변수정날짜-->
                  {{answer.modified_at|date}}
                </div>
              {% endif %}
            </div>
            <!--// 답변 날짜 종료-->
            <!-- 로그인 사용자와 답변 작성자가 같으면 -->
            {% if request.user == answer.author %}
              <div class="my-3">
                <a href="{% url 'board:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="{% url 'board:answer_delete' answer.id %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
              </div>
            {% endif %}
            <!-- 답변 댓글 영역-->
            {% if answer.comment_set.count > 0 %}
              <div class="mt-3">
                {% for comment in answer.comment_set.all %}
                  <a name="comment_{{comment.id}}"></a>
                  <div class="comment py-2 text-muted">
                    <span style="white-space:pre-line">{{comment.content}}</span>
                    <span>
                      <!--댓글 작성자 / 작성일시 / 수정일시-->
                      -
                      {{comment.author}},
                      {{comment.created_at}}
                      {% if comment.modified_at %}
                        (수정 :
                        {{comment.modified_at|date}})
                      {% endif %}
                    </span>
                    <a href="{% url 'board:comment_edit_answer' comment.id %}" class="small">수정</a>
                    <a href="{% url 'board:comment_delete_answer' comment.id %}" class="small delete">삭제</a>
                  </div>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          <div class="mx-3">
            <a href="{% url 'board:comment_create_answer' answer.id %}" class="small">댓글추가....</a>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  <div>
    <a href="{% url 'board:index' %}" class="btn btn-sm btn-primary">목록으로</a>
  </div>
  <form action="{% url 'board:answer_create' question.id %}" method="post" class="my-3">
    {% include 'errors.html' %}
    {% csrf_token %}
    <div class="form-group mb-3">
      <textarea name="content" id="content" rows="10" class="form-control"></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-success" {% if not user.is_authenticated %} disabled="disabled" {% endif %}>
  </form>

  <!-- 목록으로 클릭시 이동 폼-->
  <form action="{% url 'board:index' %}" method="get" id="actionForm">
    <input type="hidden" name="keyword" value="{{keyword|default_if_none:''}}" id="keyword">
    <input type="hidden" name="page" value="{{page|default_if_none:''}}" id="page">
    <input type="hidden" name="sort" value="{{sort|default_if_none:''}}" id="sort">
  </form>

{% endblock contents %}
{% block script %}
  <script src="{% static 'js/detail.js' %}"></script>
{% endblock script %}

board/templates/board/question_edit.html
{% extends 'base.html' %}
{% block contents %}
  <h5 class="my-3 border-bottom pb-2">질문 수정</h5>
  <!-- views.py 의 is_valid() 통과 못할 때-->
  {% include 'errors.html' %}
  <form method="post" class="my-3">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="subject">제목</label>
      <input type="text" name="subject" id="subject" class="form-control" value="{{form.subject.value|default_if_none:''}}">
    </div>
    <div class="form-group mb-3">
      <label for="content">내용</label>
      <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
    </div>
    <input type="submit" value="질문수정" class="btn btn-success">
  </form>
{% endblock contents %}

{{form.as_p}}