board/blogs/urls.py
from django.urls import path, include
from .views import (
    post_list,
    post_create,
    post_edit,
    post_delete,
    post_detail,
    post_like,
)

app_name = "blog"

urlpatterns = [
    # http://127.0.0.1:8000/blogs/
    path("", post_list, name="post_list"),
    # http://127.0.0.1:8000/blogs/create
    path("create/", post_create, name="post_create"),
    # http://127.0.0.1:8000/blogs/detail/1/
    path("detail/<int:post_id>/", post_detail, name="post_detail"),
    # http://127.0.0.1:8000/blogs/edit/1/
    path("edit/<int:post_id>/", post_edit, name="post_edit"),
    # http://127.0.0.1:8000/blogs/delete/1/
    path("delete/<int:post_id>/", post_delete, name="post_delete"),
    # http://127.0.0.1:8000/blogs/likes/1/
    path("likes/<int:post_id>/", post_like, name="post_like"),
]

board/config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views.base_views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("users/", include("users.urls")),
    path("blogs/", include("blogs.urls")),
    # http://127.0.0.1:8000/
    path("", index, name="index"),
]

board/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:login"),
        ),
        name="password_change",
    ),
]

board/board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question, QuestionCount

from django.core.paginator import Paginator

# 필터링 여러 개 조건 사용할 때 이용
from django.db.models import Q, Count

from tools.utils import get_client_ip


"""
페이지 나누기
Paginator 클래스
Paginator(전체리스트, 페이지당 보여줄개수)

has_previous : 이전 페이지 유무
has_next : 다음 페이지 유무

previous_page_number : 이전 페이지 번호
next_page_number : 다음 페이지 번호
number : 현재 페이지 번호
page_range : 페이지 범위
count : 전체 게시물 개수
start_index : 현재 페이지 인덱스(1부터 시작)
"""


def index(request):
    # 질문 목록

    # 페이지 나누기 - 사용자가 요청한 페이지 가져오기
    # http://127.0.0.1:8000/board/?keyword=테스트&page=1&sort=recommend
    # page = request.GET['page']
    page = request.GET.get("page", 1)
    keyword = request.GET.get("keyword", "")
    sort = request.GET.get("sort", "recent")

    # select * from question
    # question_list = Question.objects.all()

    # select * from question order by created_at desc
    if sort == "recommend":  # 추천순
        question_list = Question.objects.annotate(num_voter=Count("voter")).order_by(
            "-num_voter", "-created_at"
        )
    elif sort == "popular":  # 인기순
        question_list = Question.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-created_at"
        )
    else:  # 최신순
        question_list = Question.objects.order_by("-created_at")

    # 전체 질문 리스트에서 검색어를 기준으로 필터링 하기
    # 제목,내용,질문작성자,답변작성자
    # __contains : 대소문자 구별, __icontains : 대소문자 구별없이
    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword)
            | Q(content__icontains=keyword)
            | Q(author__username__icontains=keyword)
            | Q(answer__author__username__icontains=keyword)
        ).distinct()

    paginator = Paginator(question_list, 10)
    # pageinator 사용자가 요청한 페이지 정보 담기
    page_obj = paginator.get_page(page)

    context = {
        "question_list": page_obj,
        "page": page,
        "keyword": keyword,
        "sort": sort,
    }

    return render(request, "board/question_list.html", context)


def question_detail(request, qid):
    page = request.GET.get("page")
    keyword = request.GET.get("keyword")
    sort = request.GET.get("sort")

    # qid 조회
    # select * from question where id=qid
    # get_object_or_404(), get(), filter()
    question = get_object_or_404(Question, id=qid)
    # question = Question.objects.get(id=qid)

    # 조회수 증가
    # client ip 가져오기
    ip = get_client_ip(request)

    cnt = QuestionCount.objects.filter(ip=ip, question=question).count()

    if cnt == 0:
        # QuestionCount 테이블에 ip와 question 추가
        qc = QuestionCount(ip=ip, question=question)
        qc.save()
        # Question 테이블에 조회수 증가
        if question.view_cnt:
            question.view_cnt += 1
        else:
            question.view_cnt = 1
        question.save()

    context = {
        "question": question,
        "page": page,
        "keyword": keyword,
        "sort": sort,
    }

    return render(request, "board/question_detail.html", context)

board/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block style %}{% endblock style %}
  </head>

  <body>
    {% include 'navbar.html' %}
    <div class="container">
      {% block contents %}{% endblock contents %}
    </div>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block script %}{% endblock script %}
  </body>

</html>

board/templates/errors.html
{% if form.errors %}
  <div class="alert alert-danger">
    {% for field in form %}
      {% if field.errors %}
        <strong>{{field.label}}</strong>
        {{field.errors}}
      {% endif %}
    {% endfor %}
  </div>
{% endif %}

board/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">MyApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        <a class="nav-link" aria-current="page" href="{% url 'blog:post_list' %}">Blog</a>
        {% if not user.is_authenticated %}
          <a class="nav-link" href="{% url 'users:login' %}">로그인</a>
        {% else %}
          <!-- request.user : 로그인 성공시 user 정보 가져오기 -->
          <a class="nav-link" href="{% url 'users:logout' %}">{{user.username}}
            로그아웃</a>
          <a class="nav-link" href="{% url 'users:password_change' %}">비밀번호 변경</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>