myapp2/app1/urls.py
from django.urls import path
from .views import detail,info

# 앱의 네임스페이스 지정
app_name = "app1"

urlpatterns = [
    path("", detail, name="detail"),
    path("info/", info, name="info"),
]

myapp2/app2/urls.py
from django.urls import path
from .views import index

# 앱의 네임스페이스 지정
app_name = "app2"

urlpatterns = [
    path("", index, name="detail"),
]

myapp2/config/urls.py
from django.contrib import admin
from django.urls import path,include
from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include("app1.urls")),
    path('app2/', include("app2.urls")),
    path('users/', include("users.urls")),
    # http://127.0.0.1:8000/
    path("", index, name="index"),
]

myapp2/users/urls.py
from django.urls import path
from . import views

# 앱의 네임스페이스 지정
app_name = "users"

urlpatterns = [
    # http://127.0.0.1:8000/users/
    path("", views.user_main, name="main"),
    # http://127.0.0.1:8000/users/register/
    path("register", views.signup, name="register"),
    # http://127.0.0.1:8000/users/login/
    path("login", views.common_login, name="login"),
    # http://127.0.0.1:8000/users/logout/
    path("logout", views.common_logout, name="logout"),
]

myapp2/app1/models.py
from django.db import models

# Create your models here.

myapp2/app2/models.py
from django.db import models

# Create your models here.

myapp2/users/models.py
from django.db import models

# Create your models here.

myapp2/users/forms.py
from django import forms

# 장고에서 제공하는 User 생성폼과 모델 가져오기
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    """
    forms.ModelForm
        |
    BaseuserCreationForm : username, password1, password2
        |
    UserCreationForm
        |
    UserForm : User 테이블 모든 필드 + 상속

    UserCreationForm 클래스를 상속받는 Form 정의
    """

    # 부모가 넘겨주는 email 은 필수 입력 요소가 아님
    # 필수 입력 요소로 만들기 위해 재정의
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        # fields = "__all__" + 상속  # __all__ : user 테이블의 모든 필드
        fields = ["username", "email"]  # + 상속(password1, password2)

myapp2/app1/views.py
from django.shortcuts import render

def detail(request):
    return render(request, "app1/detail.html")

def info(request):
    return render(request, "app1/info.html")

myapp2/app2/views.py
from django.shortcuts import render

def index(request):
    return render(request, "app2/detail.html")

myapp2/users/views.py
from django.shortcuts import render,redirect
from .forms import UserForm
# 장고에서 제공하는 User 생성폼과 모델 가져오기
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# 로그인 처리
from django.contrib.auth import authenticate, login, logout


def index(request):
    return render(request, "index.html")

def user_main(request):
    return render(request, "users/main.html")

# def signup(request):
#     """
#     회원가입 시 UserCreationForm(아이디, 비밀번호, 비밀번호확인) 사용 방식
#     """
#     if request.method == "POST":
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("users:login")
#     else:
#         form = UserCreationForm()

#     return render(request, "users/register.html",{"form":form})

def signup(request):
    """
    회원가입 시 UserForm 사용 방식
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("users:login")
    else:
        form = UserForm()

    return render(request, "users/register.html",{"form":form})

def common_login(request):

    if request.method == "POST":
        # 사용자 입력값 가져오기
        username = request.POST["username"]
        password = request.POST["password"]
        # 사용자가 존재한다면 권한을 가진 user 객체를 리턴해줌
        user = authenticate(request, username=username, password=password)

        if user is not None:
            # 세션에 정보가 담기게 됨
            login(request, user)
            return redirect("index")

    return render(request, "users/login.html")

def common_logout(request):
    logout(request)
    return redirect("index")

myapp2/templates/app1/detail.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
  <h1>App1 Detail</h1>
  <a href="{% url 'app1:info' %}" class="btn btn-success">이동</a>
  <img src="{% static 'img/bg2.jpg' %}" alt="">
{% endblock contents %}

myapp2/templates/app1/info.html
{% extends 'base.html' %}
{% block contents %}
  <a href="{% url 'app1:detail' %}" class="btn btn-success">이동</a>
{% endblock contents %}

myapp2/templates/app2/detail.html
{% extends 'base.html' %}
{% block contents %}
  <h1>App2 Detail</h1>
{% endblock contents %}

myapp2/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>

  <body>
    <div class="container">
      {% block contents %}{% endblock contents %}
    </div>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>

</html>

myapp2/templates/errors.html
{% if form.errors %}
  <div class="alert alert-danger">
    {% for field in form %}
      {% if field.errors %}
        <strong>{{field.label}}</strong>
        {{field.errors}}
      {% endif %}
    {% endfor %}
  </div>
{% endif %}

myapp2/templates/index.html
{% extends 'base.html' %}
{% block contents %}
  <h1>INDEX -
    {{request.user}}</h1>
  <ul>
    <li>
      <a href="{% url 'app1:detail' %}">app1</a>
    </li>
    <li>
      <a href="{% url 'app2:detail' %}">app2</a>
    </li>
    <li>
      <a href="{% url 'users:main' %}">users</a>
    </li>
  </ul>
{% endblock contents %}

myapp2/templates/users/login.html
{% extends 'base.html' %}
{% block contents %}
  <div class="row my-3">
    <div class="col-4">
      <h3>로그인</h3>
    </div>
    <div class="col-8">
      <span>또는
        <a href="{% url 'users:register' %}">회원가입 하세요</a>
      </span>
    </div>
  </div>
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="username">사용자ID</label>
      <input type="text" class="form-control" name="username" id="username">
    </div>
    <div class="form-group mb-3">
      <label for="password">비밀번호</label>
      <input type="password" class="form-control" name="password" id="password">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">로그인</button>
    </div>
  </form>
{% endblock contents %}

myapp2/templates/users/main.html
{% extends 'base.html' %}
{% block contents %}
  <h1 class="pt-3">User Main</h1>
  <ul>
    <li>
      {% if user.is_authenticated %}
        <a href="{% url 'users:logout' %}">{{user.username}}logout</a>
      {% else %}
        <a href="{% url 'users:login' %}">login</a>
      {% endif %}
    </li>
    <li>
      <a href="{% url 'users:register' %}">register</a>
    </li>
  </ul>
{% endblock contents %}

myapp2/templates/users/register.html
{% extends 'base.html' %}
{% block contents %}
<div class="row my-3">
    <div class="col-4">
        <h3>회원가입</h3>        
    </div>
    <div class="col-8">
        <span>또는 <a href="{% url 'users:login' %}">로그인 하세요</a></span>
    </div>
</div>
{% include "errors.html" %}
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group mb-3">
            <label for="{{field.id_for_label}}">{{field.label}}</label>
            <input type="{{field.field.widget.input_type}}" class="form-control" name="{{field.name}}" id="{{field.id_for_label}}">
        </div>
    {% endfor %}
    <div class="form-group">
        <button type="submit" class="btn btn-primary">회원가입</button>
    </div>
</form>
{% endblock contents %}
{% comment %} {{form.as_p}} {% endcomment %}